# Generated by Django 2.2 on 2019-04-24 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=200, verbose_name='Module')),
                ('log_level', models.IntegerField(verbose_name='Log Level')),
                ('text', models.TextField(max_length=60000, verbose_name='Text')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=200, verbose_name='Parameter Name')),
                ('parameter_value', models.CharField(max_length=4000, verbose_name='Parameter Value')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('timezone_code', models.CharField(max_length=20, null=True, verbose_name='Time Zone')),
                ('default_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auprico_core.Language', verbose_name='Default Language')),
            ],
        ),
    ]
